language: php
php:
  - 5.4
  - hhvm
env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"
  - SYMFONY_VERSION="2.5.*"
  - SYMFONY_VERSION="2.6.*"


cache:
  directories:
    - $HOME/.composer/cache

# Set up the project for testing
install:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist

# Run Tests
script:
  - php ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

# Process results
after_script:
  # Send code coverage to scrutinizer-ci.com & coveralls.io
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover  build/logs/clover.xml
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - travis_retry php coveralls.phar

# Build Matrix
matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION="2.7.*"

  allow_failures:
    - env: SYMFONY_VERSION="2.7.*"
    - php: hhvm

  fast_finish: true

notifications:
  email:
    - dev@dankempster.co.uk

branches:
  only:
    - develop
    - master
